# prefix+r to reload
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# long history, 2k default
set-option -g history-limit 100000

# vi-style key bindings in copy mode, etc
set-window-option -g mode-keys vi

# Trying out mouse mode for now, use shift to bypass to local emulator
bind-key m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

# F12 to toggle whether tmux commands affect local or nested (remote) session
bind -T root F12 \
  set prefix None \;\
  set key-table off \;\
  refresh-client -S

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  refresh-client -S

