# font
font_size 14.0

# bell
enable_audio_bell no

# scrollback
scrollback_lines 1000000
map ctrl+shift+f show_scrollback
action_alias save_scrollback launch --stdin-source=@screen_scrollback --type=background
map ctrl+shift+s save_scrollback sh -c 'cat > "$HOME/kitty-$(date +%Y%m%d-%H%M%S).txt"'

# initial window
remember_window_size no
initial_window_width 100c
initial_window_height 25c

# opacity
dynamic_background_opacity yes
map ctrl+shift+o set_background_opacity 0.0
map ctrl+shift+u set_background_opacity 0.5
map ctrl+shift+i set_background_opacity 1.0
map ctrl+shift+[ set_background_opacity -0.1
map ctrl+shift+] set_background_opacity +0.1

# splitting
enabled_layouts splits:split_axis=vertical
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+slash launch --location=vsplit --cwd=current

# vi-style window navigation
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# tab bar
tab_bar_style separator
tab_separator " │ "
tab_title_template "{index}"
active_tab_title_template "{index}: {title}"
tab_title_max_length 14
